---
- hosts: nas:slurm

  #vars_files:
  #  - vars/nfs.yml

  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: vars/nfs_{{ ansible_facts['distribution'] }}.yml

    - name: Include role
      include_role:
        name: nfs

