---
- hosts: all

  tasks:
    - name: internal interface default to trusted zone
      ansible.posix.firewalld:
        zone: trusted
        interface: enp1s0
        permanent: yes
        state: enabled
      become: yes

    - name: dnf install python3-libsemanage
      ansible.builtin.dnf:
        name: python3-libsemanage
        state: present
      become: yes
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_selinux.status == "enabled"

