---
# Basic software
- name: pacman -S vim nano htop neofetch
  community.general.pacman:
    name:
      - vim
      - nano
      - htop
      - neofetch
    state: present
  become: true
  when:
    - ansible_distribution == "Archlinux"
    - "'slurm_login_node' in group_names"

- name: apt install vim nano curl htop neofetch
  ansible.builtin.apt:
    name:
      - vim
      - nano
      - curl
      - htop
      - neofetch
    state: present
  become: true
  when:
    - ansible_distribution == "Debian"
    - "'slurm_login_node' in group_names"

- name: dnf install vim nano htop neofetch
  ansible.builtin.dnf:
    name:
      - vim
      - nano
      - htop
      - neofetch
    state: present
  become: true
  when:
    - ansible_distribution == "Rocky"
    - "'slurm_login_node' in group_names"


# Container
- name: pacman -S podman aardvark-dns toolbox
  community.general.pacman:
    name:
      - podman
      - aardvark-dns
      - toolbox
    state: present
  become: true
  when:
    - ansible_distribution == "Archlinux"
    - "'slurm_login_node' in group_names"

- name: apt install podman podman-toolbox
  ansible.builtin.apt:
    name:
      - podman
      - podman-toolbox
    state: present
  become: true
  when:
    - ansible_distribution == "Debian"
    - "'slurm_login_node' in group_names"

- name: dnf install podman toolbox
  ansible.builtin.dnf:
    name:
      - podman
      - toolbox
    state: present
  become: true
  when:
    - ansible_distribution == "Rocky"
    - "'slurm_login_node' in group_names"

