---
- name: pacman -S vim nano htop neofetch
  community.general.pacman:
    name:
      - vim
      - nano
      - htop
      - neofetch
    state: present
  become: true
  when:
    - ansible_distribution == "Archlinux"
    - "'slurm_login_node' in group_names"

- name: dnf install vim nano htop neofetch
  ansible.builtin.dnf:
    name:
      - vim
      - nano
      - htop
      - neofetch
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - "'slurm_login_node' in group_names"


- name: pacman -S podman fuse-overlayfs toolbox
  community.general.pacman:
    name:
      - podman
      - fuse-overlayfs
    state: present
  become: true
  when:
    - ansible_distribution == "Archlinux"
    - "'slurm_login_node' in group_names"

- name: dnf install podman toolbox
  ansible.builtin.dnf:
    name:
      - podman
      - toolbox
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - "'slurm_login_node' in group_names"
