---
- name: pacman -S nfs-utils
  community.general.pacman:
    name: nfs-utils
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: dnf install nfs-utils
  ansible.builtin.dnf:
    name: nfs-utils
    state: present
  become: true
  when: ansible_os_family == "RedHat"
