---
- name: pacman -S slurm-llnl
  community.general.pacman:
    name: slurm-llnl
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: dnf install slurm
  ansible.builtin.dnf:
    name:
      - slurm
      - slurm-slurmctld
      - slurm-slurmd
    state: present
  become: true
  when: ansible_os_family == "RedHat"
