---
- import_tasks: install_slurm.yml

- include_tasks: slurm_setup.yml

- name: Add all cluster nodes to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.ip }}\\s+{{ item.hostname }}"
    line: "{{ item.ip }}    {{ item.hostname }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  loop: "{{ slurm_nodes_hosts }}"

- name: Create user groups if not exists
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  become: true
  loop: "{{ user_groups }}"

- name: Create user accounts
  include_tasks: user_accounts.yml
  loop: "{{ user_accounts }}"
  loop_control:
    loop_var: username

- name: nvidia.yml
  include_tasks: nvidia.yml
  when: "'nvidia_gpu_nodes' in group_names"
