---
- name: Only admins could ssh into non-login nodes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: AllowUsers {{ admins }}
    insertafter: '#\s*AllowUsers'
    validate: /usr/sbin/sshd -T -f %s
  become: true
  when:
    - "'slurm_login_node' not in group_names"
    - admins is defined

- import_tasks: install_nfs.yml

- include_tasks: nfs_server.yml
  when: "'slurm_control_node' in group_names"

- include_tasks: nfs_client.yml
  when: "'slurm_control_node' not in group_names"

- import_tasks: install_slurm.yml

- include_tasks: slurm_setup.yml

- name: slurm_users.yml
  include_tasks: slurm_users.yml
  loop: "{{ slurm_users }}"
  loop_control:
    loop_var: slurm_user

- name: nvidia.yml
  include_tasks: nvidia.yml
  when: "'nvidia_gpu_nodes' in group_names"
