---
- name: Create bind mount point /srv/nfs/home
  ansible.builtin.file:
    path: /srv/nfs/home
    state: directory
  become: true

- name: Add bind mount /srv/nfs/home to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^/home\\s+/srv/nfs/home"
    line: "/home  /srv/nfs/home  none  bind  0 0"
    state: present
  become: true

- name: add root mount to /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: "^/srv/nfs\\s+"
    line: "/srv/nfs  {{ slurm_cluster_ip }}(ro,sync,nocrossmnt,fsid=0)"
    state: present
  become: true

- name: add /srv/nfs/home mount point to /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: "^/srv/nfs/home\\s+"
    line: "/srv/nfs/home  {{ slurm_cluster_ip }}(rw,sync)"
    state: present
  become: true

- name: systemctl enable nfs-server.service
  ansible.builtin.systemd:
    name: nfs-server
    enabled: true
  become: true

#- name: firewall rule
#  ansible.posix.firewalld:
#    rich_rule: rule family=ipv4 source address="{{ item }}" service name="nfs" accept
#    permanent: true
#    immediate: true
#    state: enabled
#  loop: "{{ cluster_ip }}"
#  become: true

