---
- name: pacman -S nvidia
  community.general.pacman:
    name:
      - nvidia
      #- cuda
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Enable rpmfusion-nonfree (for nvidia driver and cuda)
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    disable_gpg_check: true
    state: present
  become: true
  when: ansible_distribution == "Rocky"

- name: dnf install akmod-nvidia xorg-x11-drv-nvidia-cuda
  ansible.builtin.dnf:
    name:
      - akmod-nvidia
      #- xorg-x11-drv-nvidia-cuda
    state: present
  become: true
  when: ansible_distribution == "Rocky"

- name: Add contrib non-free to apt source
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} contrib non-free
    - deb http://security.debian.org/debian-security {{ ansible_distribution_release }}-security contrib non-free
    - deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-updates contrib non-free
  when: ansible_distribution == "Debian"

- name: apt install nvidia-driver nvidia-smi
  ansible.builtin.apt:
    name:
      - nvidia-driver
      - nvidia-smi
    state: present
  become: true
  when: ansible_distribution == "Debian"


- name: copy gres.conf
  ansible.builtin.copy:
    src: "{{ slurm_gres_config_file }}"
    dest: "{{ slurm_conf_dir }}/gres.conf"
    owner: root
    group: root
    mode: '0644'
  become: true
