---
- name: pacman -S nvidia
  community.general.pacman:
    name:
      - nvidia
      #- cuda
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Remove kms from the HOOKS array in /etc/mkinitcpio.conf
  ansible.builtin.replace:
    path: /etc/mkinitcpio.conf
    regexp: '^(HOOKS=.+)\s+kms'
    replace: '\1 '
  become: true
  when: ansible_distribution == "Archlinux"
  register: kms_remove

- name: Regenerate the initramfs on Arch Linux
  ansible.builtin.command: mkinitcpio -P
  become: true
  when:
    - ansible_distribution == "Archlinux"
    - kms_remove.changed

- name: Check sbctl commad
  ansible.builtin.stat:
    path: /usr/bin/sbctl
  when: ansible_distribution == "Archlinux"
  register: sbctl_cmd

- name: Re-sign unified kernel image if sbctl exist on Arch Linux
  ansible.builtin.command: sbctl sign-all
  become: true
  when:
    - ansible_distribution == "Archlinux"
    - kms_remove.changed
    - sbctl_cmd.stat.exists

- name: Add contrib non-free to apt source
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  become: true
  loop:
    - deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} contrib non-free
    - deb http://security.debian.org/debian-security {{ ansible_distribution_release }}-security contrib non-free
    - deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-updates contrib non-free
  when: ansible_distribution == "Debian"

- name: apt install nvidia-driver nvidia-smi
  ansible.builtin.apt:
    name:
      - nvidia-driver
      - nvidia-smi
    state: present
  become: true
  when: ansible_distribution == "Debian"

- name: Enable rpmfusion-nonfree (for nvidia driver and cuda)
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    disable_gpg_check: true
    state: present
  become: true
  when: ansible_distribution == "Rocky"

- name: dnf install akmod-nvidia xorg-x11-drv-nvidia-cuda
  ansible.builtin.dnf:
    name:
      - akmod-nvidia
      #- xorg-x11-drv-nvidia-cuda
    state: present
  become: true
  when: ansible_distribution == "Rocky"


- name: copy gres.conf
  ansible.builtin.copy:
    src: "{{ slurm_gres_config_file }}"
    dest: "{{ slurm_conf_dir }}/gres.conf"
    owner: root
    group: root
    mode: '0644'
  become: true
