---
- name: copy munge.key
  ansible.builtin.copy:
    src: "{{ munge_key_file }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  become: true
  register: munge_key_file

- name: systemctl enable --now munge.service
  ansible.builtin.systemd: name=munge.service enabled=true state=started
  become: true

- name: set slurm_conf_dir (Archlinux)
  set_fact:
    slurm_conf_dir: /etc/slurm-llnl
  when: ansible_distribution == "Archlinux"

- name: set slurm_conf_dir (Rocky)
  set_fact:
    slurm_conf_dir: /etc/slurm
  when: ansible_os_family == "RedHat"

- name: copy slurm.conf to all nodes
  ansible.builtin.copy:
    src: "{{ slurm_config_file }}"
    dest: "{{ slurm_conf_dir }}/slurm.conf"
    owner: root
    group: root
    mode: '0644'
  become: true
  register: slurm_conf

- name: copy cgroup.conf to all compute nodes
  ansible.builtin.copy:
    src: "{{ slurm_cgroup_config_file }}"
    dest: "{{ slurm_conf_dir }}/cgroup.conf"
    owner: root
    group: root
    mode: '0644'
  become: true
  when:
    - "'slurm_compute_nodes' in group_names"

- name: Create user slurm
  ansible.builtin.user:
    name: slurm
    uid: 64030
    password: '!'
    password_lock: true
    shell: "/usr/bin/nologin"
    create_home: false
    state: present
  become: true

- name: Slurm run as user slurm (not root)
  ansible.builtin.shell: |
    systemctl stop slurmd.service
    systemctl stop slurmctld.service
    slurm-setuser -u slurm -g slurm -y
  become: true
  when:
    - ansible_os_family == "RedHat"
    - slurm_conf.changed

- name: start and enable slurmd.service on all compute nodes
  ansible.builtin.systemd: name=slurmd.service enabled=true state=started
  become: true
  when: "'slurm_compute_nodes' in group_names or 'slurm_login_node' in group_names"

- name: start and enable slurmctld.service on all control nodes
  ansible.builtin.systemd: name=slurmctld.service enabled=true state=started
  become: true
  when: "'slurm_control_node' in group_names"

- name: Create groups if not exists
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  become: true
  loop: "{{ slurm_groups }}"

- name: Add all cluster nodes to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.ip }}\\s+{{ item.hostname }}"
    line: "{{ item.ip }}    {{ item.hostname }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  loop: "{{ slurm_nodes_hosts }}"

