---
- name: copy munge.key
  ansible.builtin.copy:
    src: "{{ munge_key_file }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  become: yes
  register: munge_key_file

- name: systemctl enable --now munge.service
  ansible.builtin.systemd:
    name: munge.service
    enabled: yes
    state: started
  become: yes

- name: copy slurm.conf to all nodes (Arch Linux)
  ansible.builtin.copy:
    src: "{{ slurm_config_file }}"
    dest: /etc/slurm-llnl/slurm.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: copy slurm.conf to all nodes (Rocky Linux)
  ansible.builtin.copy:
    src: "{{ slurm_config_file }}"
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: ansible_facts['os_family'] == "RedHat"
  register: slurm_conf

- name: copy cgroup.conf to all compute nodes (Arch Linux)
  ansible.builtin.copy:
    src: "{{ slurm_cgroup_config_file }}"
    dest: /etc/slurm-llnl/cgroup.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - "'slurm_cpu_nodes' in group_names"
    - ansible_facts['os_family'] == "Archlinux"

- name: copy cgroup.conf to all compute nodes (Rocky Linux)
  ansible.builtin.copy:
    src: "{{ slurm_cgroup_config_file }}"
    dest: /etc/slurm/cgroup.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - "'slurm_cpu_nodes' in group_names"
    - ansible_facts['os_family'] == "RedHat"

- name: Create user slurm
  ansible.builtin.user:
    name: slurm
    uid: 64030
    password: '!'
    password_lock: true
    shell: "/usr/bin/nologin"
    create_home: false
    state: present
  become: yes

- name: Slurm run as user slurm (not root)
  ansible.builtin.shell: |
    systemctl stop slurmd.service
    systemctl stop slurmctld.service
    slurm-setuser -u slurm -g slurm -y
  become: yes
  when:
    - ansible_facts['os_family'] == "RedHat"
    - slurm_conf.changed

- name: start and enable slurmd.service on all compute nodes
  ansible.builtin.systemd:
    name: slurmd.service
    enabled: yes
    state: started
  become: yes
  when: "'slurm_cpu_nodes' in group_names"

- name: start and enable slurmctld.service on all control nodes
  ansible.builtin.systemd:
    name: slurmctld.service
    enabled: yes
    state: started
  become: yes
  when: "'slurm_control_nodes' in group_names"

- name: Create groups if not exists
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  become: yes
  loop: "{{ slurm_groups }}"

- name: Add all cluster nodes to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ item.hostname }}"
    line: "{{ item.ip }}    {{ item.hostname }}"
    owner: root
    group: root
    mode: '0644'
  become: yes
  loop: "{{ slurm_nodes }}"

