---
- name: create user without home directory (non-control nodes)
  ansible.builtin.user:
    name: "{{ username.name }}"
    uid: "{{ username.uid }}"
    groups: "{{ username.addition_groups }}"
    password: "{{ username.password }}"
    update_password: on_create
    create_home: false
    state: "{{ username.state }}"
    remove: true
  become: true
  when: "'slurm_control_node' not in group_names"

- name: create user with home directory (control node)
  ansible.builtin.user:
    name: "{{ username.name }}"
    uid: "{{ username.uid }}"
    groups: "{{ username.addition_groups }}"
    password: "{{ username.password }}"
    update_password: on_create
    create_home: true
    state: "{{ username.state }}"
    remove: true
  become: true
  when: "'slurm_control_node' in group_names"

- name: Create .ssh directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ username.name }}/.ssh"
    state: directory
    owner: "{{ username.name }}"
    group: "{{ username.name }}"
    mode: '0700'
  become: true
  when: "'slurm_control_node' in group_names"

- name: Copy ssk key
  ansible.builtin.copy:
    content: |
      {{ username.ssh_public_key }}
    dest: /home/{{ username.name }}/.ssh/authorized_keys
    force: false
    owner: "{{ username.name }}"
    group: "{{ username.name }}"
    mode: '0600'
  become: true
  when: "'slurm_control_node' in group_names"
