---
munge_key_file: files/slurm/munge.key.example
slurm_config_file: files/slurm/slurm.conf.Rocky
slurm_cgroup_config_file: files/slurm/cgroup.conf.Rocky
slurm_gres_config_file: files/slurm/gres.conf.Rocky

# The ip/mask of the cluster
slurm_cluster_ip: 192.168.124.0/24

# The control node ip
slurm_control_node_ip: 192.168.124.10

# all nodes and its ip address, appended to /etc/hosts file
slurm_nodes_hosts:
  - { hostname: rocky0, ip: 192.168.124.1 }
  - { hostname: rocky10, ip: 192.168.124.10 }
  - { hostname: rocky11, ip: 192.168.124.11 }
  - { hostname: rocky12, ip: 192.168.124.12 }

# Encrypt this file using for example ansible vault to prevent leak user info.
slurm_users:
  - name: johnsmith
    uid: 1234
    state: present
    password: $6$mysecretsalt$ZB9R8AirQYAXhtfhOo2qdJz52FyNI6v3L6Uc3KNRP.arBKIYpcuEyQewT5qBAHoyQFwHkW6Z551Ql.cZ53GeY0
    addition_groups: secret_group,another_group
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3uVHbEg3FnFodk/2fpDD/U1Ousnrqke8i2WP855zVN

slurm_groups:
  - { name: secret_group, gid: 12345, state: present }
  - { name: another_group, gid: 23456, state: present }
