---
- name: setsebool -P use_nfs_home_dirs=true
  ansible.posix.seboolean:
    name: use_nfs_home_dirs
    state: true
    persistent: true
  when: ansible_selinux.status == "enabled"
  become: true

- name: Create mount point
  ansible.builtin.file:
    path: "{{ nfs_share.client_mount_point }}"
    state: directory
    owner: "{{ nfs_share.owner }}"
    group: "{{ nfs_share.group }}"
    mode: "{{ nfs_share.mode }}"
  become: true

- name: Add nfs mount point to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "\\s+{{ nfs_share.client_mount_point }}\\s+"
    line: "{{ nfs_share.server_ip }}:/{{ nfs_share.name }}    {{ nfs_share.client_mount_point }}    nfs    {{ nfs_share.mount_opts }}    0 0"
    state: present
  become: true
  notify:
    - remount

