---
- block:
  - name: Create NFS directories
    ansible.builtin.file:
      path: "{{ item.bind }}"
      state: directory
    loop: "{{ nfs_mount_point }}"

  - name: Add bind mount to /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: "^{{ item.target }}\\s+{{item.bind }}"
      line: "{{ item.target }}  {{item.bind }}  none  bind  0 0"
      state: present
    loop: "{{ nfs_mount_point }}"

  - name: add root mount to /etc/exports
    ansible.builtin.lineinfile:
      path: /etc/exports
      regexp: "^{{ nfs_root }}\\s+"
      line: "{{ nfs_root }}  {{ nfs_root_opt }}"
      state: present

  - name: add other mount points to /etc/exports
    ansible.builtin.lineinfile:
      path: /etc/exports
      regexp: "^{{ item.bind }}\\s+"
      line: "{{ item.bind }}  {{ item.opt }}"
      state: present
    loop: "{{ nfs_mount_point }}"

  - name: systemctl enable nfs-server.service
    ansible.builtin.systemd:
      name: nfs-server
      enabled: yes
  become: yes

