---
- include_tasks: "{{ ansible_distribution }}.yml"

- name: Limit processes (prevent fork bombs)
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: true
  loop:
    - { regexp: '^\*\s+soft\s+nproc', line: '* soft nproc 1000' }
    - { regexp: '^\*\s+hard\s+nproc', line: '* hard nproc 1000' }

